ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: tests/GalSim/|tests/Coord/|tests/jax/galsim/
      - id: ruff-format
        exclude: tests/GalSim/|tests/Coord/|tests/jax/galsim/
  - repo: local
    hooks:
    - id: update-readme-with-apis
      name: update readme with apis
      entry: python scripts/update_api_coverage.py
      language: system
      files: README.md
      require_serial: true
